# Generated by Django 4.0.5 on 2022-11-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='materials_provide',
        ),
        migrations.AlterField(
            model_name='form',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
